build/pkgs/sagemath_objects/spkg-install: Rephrase messages using 'baseline'

diff --git a/build/pkgs/sagemath_objects/spkg-install b/build/pkgs/sagemath_objects/spkg-install
--- a/build/pkgs/sagemath_objects/spkg-install
+++ b/build/pkgs/sagemath_objects/spkg-install
@@ -24,10 +24,25 @@ python3 -m build --outdir "$DIST_DIR"/dist . || sdh_die "Failure building sdist 
 wheel=$(cd "$DIST_DIR" && sdh_store_wheel . >&2 && echo $wheel)
 ls -l "$wheel"
 
-export TOX_PARALLEL_NO_SPINNER=1
-
-if [ "$SAGE_CHECK" = no ]; then
-    (set -x; tox -r -p auto -v --installpkg $wheel --notest)
-else
-    (set -x; tox -r -p auto -v --installpkg $wheel) && (ls -l $(pwd)/.tox/sagepython-sagewheels-nopypi-norequirements*/log/*-command*.log; :)
+if [ "$SAGE_CHECK" != no ]; then
+    export TOX_PARALLEL_NO_SPINNER=1
+    echo Running "tox -r -p auto -v --installpkg $wheel"
+    tox -r -p auto -v --installpkg $wheel
+    status=$?
+    case $status:$SAGE_CHECK:$([ -r known-test-failures.json ]; echo $?) in
+        0:*:0)    echo "Passed the test suite (modulo baseline known-test-failures*.json)";;
+        0:*:*)    echo "Passed the test suite";;
+        *:warn:0) echo "Warning: New failures (not in baseline known-test-failures*.json (ignored)"; status=0;;
+        *:warn:*) echo "Warning: Failures testing the package (ignored)"; status=0;;
+        *:yes:0)  echo "New failures, not in baseline known-test-failures*.json";;
+        *:yes:*)  echo "Failures testing the package";;
+    esac
+    # Show summaries of failures (suppress lines ending with '[failed in baseline]')
+    for f in $(pwd)/.tox/sagepython-sagewheels-nopypi-norequirements*/log/*-command*.log; do
+        if [ -r "$f" ]; then
+            echo "$f"
+            grep '^sage -t.*#[^]]*$' "$f"
+        fi
+    done
+    exit $status
 fi
