build/bin/sage-dist-helpers (sdh_build_wheel): New option --sdist-then-wheel

diff --git a/build/bin/sage-dist-helpers b/build/bin/sage-dist-helpers
--- a/build/bin/sage-dist-helpers
+++ b/build/bin/sage-dist-helpers
@@ -223,6 +223,8 @@ sdh_build_wheel() {
     build_options=""
     # pip has --no-build-isolation but no flag that turns the default back on...
     build_isolation_option=""
+    # build has --wheel but no flag that turns the default (build sdist and then wheel) back on
+    dist_option="--wheel"
     export PIP_FIND_LINKS="$SAGE_SPKG_WHEELS"
     unset PIP_NO_BINARY
     while [ $# -gt 0 ]; do
@@ -242,6 +244,9 @@ sdh_build_wheel() {
                 export PIP_NO_BINARY=:all:
                 build_isolation_option="--no-isolation --skip-dependency-check"
                 ;;
+            --sdist-then-wheel)
+                dist_option=""
+                ;;
             --no-deps)
                 install_options="$install_options $1"
                 ;;
@@ -257,7 +262,7 @@ sdh_build_wheel() {
         esac
         shift
     done
-    if python3 -m build --wheel --outdir=dist $build_isolation_option $build_options "$@"; then
+    if python3 -m build $dist_option --outdir=dist $build_isolation_option $build_options "$@"; then
         : # successful
     else
         case $build_isolation_option in
@@ -265,12 +270,12 @@ sdh_build_wheel() {
                 sdh_die "Error building a wheel for $PKG_NAME"
                 ;;
             *)
-                echo >&2 "Warning: building with \"python3 -m build --wheel --outdir=dist $build_isolation_option $build_options $@\" failed."
+                echo >&2 "Warning: building with \"python3 -m build $dist_option --outdir=dist $build_isolation_option $build_options $@\" failed."
                 unset PIP_FIND_LINKS
                 export PIP_NO_BINARY=:all:
                 build_isolation_option="--no-isolation --skip-dependency-check"
-                echo >&2 "Retrying with \"python3 -m build --wheel --outdir=dist $build_isolation_option $build_options $@\"."
-                if python3 -m build --wheel --outdir=dist $build_isolation_option $build_options "$@"; then
+                echo >&2 "Retrying with \"python3 -m build $dist_option --outdir=dist $build_isolation_option $build_options $@\"."
+                if python3 -m build $dist_option --outdir=dist $build_isolation_option $build_options "$@"; then
                     echo >&2 "Warning: Wheel building needed to use \"$build_isolation_option\" to succeed. This means that a dependencies file in build/pkgs/ needs to be updated. Please report this to sage-devel@googlegroups.com, including the build log of this package."
                 else
                     sdh_die "Error building a wheel for $PKG_NAME"
