build/bin/sage-logger: New option -P prefix; only prefix if LOGFILE not given

diff --git a/build/bin/sage-logger b/build/bin/sage-logger
--- a/build/bin/sage-logger
+++ b/build/bin/sage-logger
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 #
-# sage-logger [-p] COMMAND LOGFILE
+# sage-logger [-p] [-P PREFIX] COMMAND [LOGFILE]
 #
 # Evaluate shell command COMMAND while logging stdout and stderr to
-# LOGFILE. If either the command or the logging failed, return a
+# LOGFILE (if given). If either the command or the logging failed, return a
 # non-zero exit status.
 #
 # If the -p argument is given, each line printed to stdout is prefixed
 # with the name of the log file.
+#
+# If the -P PREFIX argument is given, each line printed to stdout is
+# prefixed with PREFIX.
 #
 # AUTHOR:
 #
@@ -24,11 +27,17 @@
 #*****************************************************************************
 
 use_prefix=false
+prefix=""
 
-if [[ "$1" = -p ]]; then
-    use_prefix=true
-    shift
-fi
+case "$1" in
+    -p) use_prefix=true
+        shift
+        ;;
+    -P) use_prefix=true
+        prefix="[$2] "
+        shift 2
+        ;;
+esac
 
 cmd="$1"
 logfile="$2"
@@ -36,10 +45,8 @@ export SAGE_LOGFILE="$logfile"
 logname="$(basename $logfile .log)"
 logdir=`dirname "$logfile"`
 
-if [[ $use_prefix = true ]]; then
+if [[ $use_prefix = true && -z "$prefix" ]]; then
     prefix="[${logname}] "
-else
-    prefix=""
 fi
 
 # Use sed option to reduce buffering, to make the output appear more
@@ -59,6 +66,20 @@ if [ -n "$prefix" ]; then
 else
     # Make SED a useless use of cat
     SED=cat
+fi
+
+if [ -z "$logfile" ]; then
+    # Just prefix, nothing else
+    ( exec 2>&1; sh -c "$cmd" ) | \
+        ( trap '' SIGINT; if [ -n "$GITHUB_ACTIONS" -a -n "$prefix" ]; then echo "::group::${logname}"; fi; $SED; if [ -n "$GITHUB_ACTIONS" -a -n "$prefix" ]; then echo "::endgroup::"; fi )
+
+    pipestatus=(${PIPESTATUS[*]})
+
+    if [ ${pipestatus[1]} -ne 0 ]; then
+        exit ${pipestatus[1]}
+    else
+        exit ${pipestatus[0]}
+    fi
 fi
 
 timefile="$logdir/$logname.time"
