build/bin/sage-logger [GITHUB_ACTIONS]: Do not truncate log, use ::error: annotation and ::group:

diff --git a/build/bin/sage-logger b/build/bin/sage-logger
--- a/build/bin/sage-logger
+++ b/build/bin/sage-logger
@@ -118,9 +118,16 @@ if [ -n "$SAGE_SILENT_BUILD" -a ${use_prefix} = true ]; then
     ( exec>> $logfile 2>&1; time_cmd "$cmd"; status=$?; report_time; exit $status )
     status=$?
     if [[ $status != 0 ]]; then
-        echo "  [$logname] error installing, exit status $status. End of log file:"
-        tail -n 120 "$logfile" | sed "/Please email sage-devel/,$ d;s;^;  [$logname]   ;" >&2
-        echo "  [$logname] Full log file: $logfile"
+        if [ -n "$GITHUB_ACTIONS" ]; then
+            echo :":"error file=$logfile:":" ==== ERROR IN LOG FILE $logfile ====
+            echo "::group::${logname}"
+            sed "s;^;  [$logname]   ;" "$logfile" >&2
+            echo "::endgroup::"
+        else
+            echo "  [$logname] error installing, exit status $status. End of log file:"
+            tail -n 120 "$logfile" | sed "/Please email sage-devel/,$ d;s;^;  [$logname]   ;" >&2
+            echo "  [$logname] Full log file: $logfile"
+        fi
     else
         time=$(report_time)
         if [ -n "$time" ]; then
