pkgs/sagemath-*: Support editable installs

diff --git a/build/pkgs/sagemath_mpmath/spkg-install b/build/pkgs/sagemath_mpmath/spkg-install
--- a/build/pkgs/sagemath_mpmath/spkg-install
+++ b/build/pkgs/sagemath_mpmath/spkg-install
@@ -11,53 +11,59 @@ if [ $? -ne 0 ]; then
 fi
 cd src
 
-rm -rf build *.egg_info
-
 export PIP_NO_INDEX=true
 export PIP_FIND_LINKS="file://$SAGE_DISTFILES"
 vendoring sync
 
 export PIP_FIND_LINKS="file://$SAGE_SPKG_WHEELS"
 
-# First build the sdist, then build the wheel from the sdist.
-# https://pypa-build.readthedocs.io/en/latest/#python--m-build
-DIST_DIR="$(mktemp -d)"
-python3 -m build --outdir "$DIST_DIR"/dist . || sdh_die "Failure building sdist and wheel"
-
 if [ "$SAGE_EDITABLE" = yes ]; then
-    # SAGE_ROOT/src/setup.py installs everything, nothing to install
-    wheel=$(cd "$DIST_DIR" && sdh_store_wheel . >&2 && echo $wheel)
+    tox_envs=$(tox -l | sed s/norequirements/editable/)
+    # FIXME: Should use -r if sage_setup or another build requirement changes
+    tox_args="-p auto -v -v -v -v -e $(echo $tox_envs | sed 's/ /,/g')"
+    if [ "$SAGE_CHECK" = no ]; then
+        tox_args="$tox_args --notest"
+    fi
 else
-    if [ "$SAGE_WHEELS" = yes ]; then
-        # Modularized install via wheels
-        wheel=$(cd "$DIST_DIR" && sdh_store_and_pip_install_wheel . >&2 && echo $wheel)
+    rm -Rf build
+    # First build the sdist, then build the wheel from the sdist.
+    # https://pypa-build.readthedocs.io/en/latest/#python--m-build
+    # (Important because the package uses MANIFEST.in for filtering.)
+    # Do not install the wheel.
+    DIST_DIR="$(mktemp -d)"
+    python3 -m build --outdir "$DIST_DIR"/dist . || sdh_die "Failure building sdist and wheel"
+    ls -l "$DIST_DIR"/dist/*.tar.gz
+    wheel=$(cd "$DIST_DIR" && sdh_store_wheel . >&2 && echo $wheel)
+    ls -l "$wheel"
+    if [ "$SAGE_CHECK" != no ]; then
+        tox_envs=$(tox -l)
+        tox_args="-r -p auto -v --installpkg $wheel"
     else
-        # Legacy direct installation
-        wheel=$(cd "$DIST_DIR" && sdh_store_wheel . >&2 && echo $wheel)
+        unset tox_args
     fi
 fi
 
-ls -l "$wheel"
-
-if [ "$SAGE_CHECK" != no ]; then
+if [ -n "$tox_args" ]; then
     export TOX_PARALLEL_NO_SPINNER=1
-    echo Running "tox -r -p auto -v --installpkg $wheel"
-    tox -r -p auto -v --installpkg $wheel
+    echo Running "tox $tox_args"
+    tox $tox_args
     status=$?
     case $status:$SAGE_CHECK:$([ -r known-test-failures.json ]; echo $?) in
-        0:*:0)    echo "Passed the test suite (modulo known-test-failures.json)";;
+        0:*:0)    echo "Passed the test suite (modulo baseline known-test-failures*.json)";;
         0:*:*)    echo "Passed the test suite";;
-        *:warn:0) echo "Warning: New failures, not recorded in known-test-failures.json (ignored)"; status=0;;
+        *:warn:0) echo "Warning: New failures (not in baseline known-test-failures*.json (ignored)"; status=0;;
         *:warn:*) echo "Warning: Failures testing the package (ignored)"; status=0;;
-        *:yes:0)  echo "New failures, not recorded in known-test-failures.json";;
+        *:yes:0)  echo "New failures, not in baseline known-test-failures*.json";;
         *:yes:*)  echo "Failures testing the package";;
     esac
     # Show summaries of failures (suppress lines ending with '[failed in baseline]')
-    for f in $(pwd)/.tox/sagepython-sagewheels-nopypi-norequirements*/log/*-command*.log; do
-        if [ -r "$f" ]; then
-            echo "$f"
-            grep '^sage -t.*#[^]]*$' "$f"
-        fi
+    for e in $tox_envs; do
+        for f in $(pwd)/.tox/$e/log/*-command*.log; do
+            if [ -r "$f" ]; then
+                echo "$f"
+                grep '^sage -t.*#[^]]*$' "$f"
+            fi
+        done
     done
     exit $status
 fi
